config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'landing#index'
  get 'contact', to: 'greeting#index'
  post 'contact/send', to: 'greeting#do_send'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :playgrounds, only: [:index] do
    collection do
      get :instagram_caption_maker
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact
	include ActiveModel::Validations
	include ActiveModel::Conversion
  extend ActiveModel::Naming

	attr_accessor :name, :email, :phone, :message

	validates :name, :phone, :message, presence: true
	validates :email, format: { with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i }
	validates :phone, numericality: true

	def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/landing_config.rb
class LandingConfig < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
	validates :name, :phone, presence: true, length: { maximum: 30 }
	validates :message, presence: true, length: { maximum: 200 }
	validates :email, format: { with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i }
	validates :phone, numericality: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/greeting_controller.rb
class GreetingController < ApplicationController
  def index
  end

  def do_send
  	contact = Message.new(greeting_params)
  	if contact.save
      GreetingMailer.send_email(greeting_params).deliver_later
	  	render json: { success: true, message: "OK" }
	  else
	  	render json: { success: false, message: "#{contact.errors.full_messages.join(', ')}. Please try again." }
	  end
  end

  private
  	def greeting_params
  		params.require(:message).permit(:name, :email, :phone, :message)
  	end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  	@landing_config = LandingConfig.first
  	@skills = Skill.all
  end
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  layout "application_simple"

  def index; end

  def instagram_caption_maker; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/messages/_index.html.slim
table
	thead
		th Name
		th Email
		th Phone
		th Created at
	tbody
		- messages.each do |message|
			tr
				td = link_to message.name, admin_message_path(message)
				td = message.email
				td = message.phone
				td = message.created_at.in_time_zone('Jakarta').strftime('%A, %d %B %Y - %H:%m')

app/views/landing/index.html.slim
- cache 'header'
  /! header ==================================================
  header
    .row
      .top-bar
        a.menu-toggle href="#"
          span Menu
        .logo
          a href="/"  AVID
        nav#main-nav-wrap
          ul.main-navigation
            li.current
              a.smoothscroll href="#intro" title=""  Home
            li
              a.smoothscroll href="#about" title=""  About
            li
              a.smoothscroll href="#contact" title=""  Contact
            li
              a href="/playgrounds" title=""  Playgrounds

      /! /top-bar
    /! /row
  /! /header
  /! intro section ==================================================
  section#intro
    .intro-overlay
    .intro-content
      .row
        .col-twelve
          h5 Hello, World.
          h1 It's nice to meet you.
          a.button.stroke.smoothscroll href="#about" title=""  More About Me
          / a.button.stroke.typeform-share.link href="https://avidmaulanas.typeform.com/to/QZJe3Z" data-mode="2" target="_blank" More About Me
    /! /intro-content
    ul.intro-social
      li
        a href="https://www.facebook.com/avidmaulanas" target="_blank"
          i.fa.fa-facebook
      li
        a href="https://twitter.com/avidmaulanas" target="_blank"
          i.fa.fa-twitter
      li
        a href="https://www.instagram.com/avidmaulanas" target="_blank"
          i.fa.fa-instagram
      li
        a href="https://github.com/avidmaulanas" target="_blank"
          i.fa.fa-github

    /! /intro-social
  /! /intro
  /! about section ==================================================
  section#about
    .row.section-intro
      .col-twelve
        h5 About
        h1 Let me introduce myself.
        .intro-info
          img alt=("Profile Picture") src="#{asset_path('profile-pic.jpg')}"
          p.lead
            = simple_format(@landing_config&.about_me)
    /! /section-intro
    .row.about-content
      .col-six.tab-full
        h3 Profile
        ul.info-list
          li
            strong Fullname:
            span= @landing_config&.full_name
          li
            strong Job:
            span= @landing_config&.job_title
          li
            strong Email:
            span= @landing_config&.email
        /! /info-list
      .col-six.tab-full
        h3 Skills
        ul.skill-bars
          - @skills.each do |skill|
            li
              .progress class="percent#{skill.score}"
                span= "#{skill.score}%"
              strong= skill.title

        /! /skill-bars
    .row.button-section
      .col-twelve
        a.button.stroke.smoothscroll href="#contact" title=("Contact Me")  Contact Me
  /! /process

/! contact ==================================================
section#contact
  .row.section-intro
    .col-twelve
      h5 Contact
      h1 I'd Love To Hear From You.
      p.lead If you want to send me message, please fill the form contact below. The message will sent to me.
  /! /section-intro
  .row.contact-form
    .col-twelve
      /! form
      = simple_form_for(:message, url: contact_send_path, html: {id: "contactForm"}) do |f|
        .form-field
          = f.input :name, label: false, required: true, input_html: { id: "contactName", placeholder: "Name", minlength: "2"}

        .form-field
          = f.input :email, as: :email, label: false, required: true, input_html: { id: "contactEmail", placeholder: "Email"}

        .form-field
          = f.input :phone, as: :tel, label: false, required: true, input_html: { id: "contactPhone", placeholder: "Phone", maxlength: "14", pattern: '[0-9\-\(\)\s]+'}

        .form-field
          = f.input :message, as: :text, label: false, required: true, input_html: { id: "contactMessage", placeholder: "message"}

        .form-field
          = f.submit "Send", class: "submitform"

          #submit-loader
            .text-loader Sending...
            .s-loader
              .bounce1
              .bounce2
              .bounce3
      /! Form End
      /! contact-warning
      #message-warning
      /! contact-success
      #message-success
        i.fa.fa-check
        | Your message was sent, thank you!
        br/
    /! /col-twelve
  /! /contact-form
  - cache 'contact'
    .row.contact-info
        -#.col-four.tab-full
        -#  .icon
        -#    i.icon-pin
        -#  h5 Where to find me
        -#  = simple_format(@landing_config&.address)

        -#.col-four.tab-full.collapse
        -#.text-center
        -#  .icon
        -#    i.icon-mail
        -#  h5 Email Me At
        -#  p= @landing_config&.email

        -#.col-four.tab-full
        -#  .icon
        -#    i.icon-phone
        -#  h5 Call Me At
        -#  p= @landing_config&.phone

  /! /contact-info
/! /contact
- cache 'footer'
  /! footer ==================================================
  footer
    .row
      .col-six.tab-full.pull-right.social
        ul.footer-social
          li
            a href="https://www.facebook.com/avidmaulanas" target="_blank"
              i.fa.fa-facebook
          li
            a href="https://twitter.com/avidmaulanas" target="_blank"
              i.fa.fa-twitter
          li
            a href="https://www.instagram.com/avidmaulanas" target="_blank"
              i.fa.fa-instagram
          li
            a href="https://github.com/avidmaulanas" target="_blank"
              i.fa.fa-github
      .col-six.tab-full
        .copyright
          span
            | Design by
            a href="http://www.styleshout.com/" target="_blank"  styleshout
      #go-top
        a.smoothscroll href="#top" title=("Back to Top")
          i.fa.fa-long-arrow-up
    /! /row
#preloader
  #loader

app/views/layouts/application.html.slim
doctype html
/![if IE 8 ] <html class="no-js oldie ie8" lang="en"
/![if IE 9 ] <html class="no-js oldie ie9" lang="en"
/! [if (gte IE 9)|!(IE)]><!
html.no-js lang="en"
  /! <![endif]

  head
    title Avid Maulana Saputra

    meta content="Portfolio, Resume, CV, Job, Freelance, Work, Back-end developer" name="description"
		meta content="Avid Maulana Saputra" name="author"
    meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = favicon_link_tag 'favicon.png'
    = csrf_meta_tags
    -#= analytics_init if GoogleAnalytics.valid_tracker?

  BODY id="top"
    = yield
    = javascript_include_tag 'jquery-2.1.3.min.js', 'data-turbolinks-track' => true
    = javascript_include_tag 'plugins.js', 'data-turbolinks-track' => true
    = javascript_include_tag 'main.js', 'data-turbolinks-track' => true
    = javascript_include_tag 'typeform.js', 'data-turbolinks-track' => true

app/views/layouts/application_simple.html.slim
doctype html
/![if IE 8 ] <html class="no-js oldie ie8" lang="en"
/![if IE 9 ] <html class="no-js oldie ie9" lang="en"
/! [if (gte IE 9)|!(IE)]><!
html.no-js lang="en"
  /! <![endif]

  head
    title
      | Avid Maulana Saputra
      - if action_name.present? && !action_name.eql?('index')
        | &nbsp;
        | -
        | &nbsp;
        = action_name.to_s.titleize


    meta content="Portfolio, Resume, CV, Job, Freelance, Work, Back-end developer" name="description"
		meta content="Avid Maulana Saputra" name="author"
    meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport"

    = favicon_link_tag 'favicon.png'
    -#= csrf_meta_tags

  BODY id="top"
    = yield
    = javascript_include_tag 'jquery-2.1.3.min.js', 'data-turbolinks-track' => true
    = yield :javascripts

app/views/playgrounds/index.html.slim
section
  = link_to "Back to Home", root_path

section
  h1 Playgrounds

section
  ul
    li= link_to "Instagram Caption Maker", instagram_caption_maker_playgrounds_path

app/views/playgrounds/instagram_caption_maker.html.slim
section
  = link_to "Homepage", root_path
  | &nbsp; - &nbsp;
  = link_to "Playgrounds", playgrounds_path
  | &nbsp; - &nbsp; Instagram Caption Maker

section
  h1 Instagram Caption Maker
  p Easy add new line. Convert and paste!

section
  .content
    = text_area_tag :content, nil, rows: 15, cols: 50
  .convert
    = button_tag "Convert", class: "btn-convert"
    | &nbsp;
    = button_tag "Clear", class: "btn-clear"

section
  p
    | Follow me on Instagram:
    | &nbsp;
    = link_to "@avidmaulanas", "https://www.instagram.com/avidmaulanas", target: "_blank", style: "text-decoration:none;"

- content_for :javascripts do
  javascript:
    $('.btn-convert').on('click', function(){
      convertContent();
    });

    $('.btn-clear').on('click', function(){
      clearContent();
    });

    function convertContent(){
      var content = $('#content').val();

      // convert line break
      content = content.replace(/(?:\r\n|\r|\n)/g, "\u2063\n");

      // replace content
      $('#content').val(content);

      // select all content
      $('#content').select();

      // execute copy command
      document.execCommand('copy');
    }

    function clearContent(){
      $('#content').val('');
    }